export const fakeStore = {
  movies: {
    popularMovies: null,
    loadingPopularMovies: false,
    errorPopularMovies: null,
    topRatedMovies: null,
    loadingTopRatedMovies: false,
    errorTopRatedMovies: null,
    latestMovie: null,
    loadingLatestMovie: false,
    errorLatestMovie: null,
  },
  movie: { movieInfo: null, loading: false, error: null },
  favorites: {
    favoritesList: null,
    loadingFavList: false,
    errorFavList: null,
    favorites: null,
    loadingFavs: false,
    errorFavs: null,
    addFavorite: null,
    loadingAddFav: false,
    errorAddFav: null,
    removeFavorite: null,
    loadingRemFav: false,
    errorRemFav: null,
  },
  seen: {
    seenList: null,
    loadingSeenList: false,
    errorSeenList: null,
    seen: null,
    loadingSeen: false,
    errorSeen: null,
    addSeen: null,
    loadingAddSeen: false,
    errorAddSeen: null,
  },
};
