// Favorites
// -----List of ids------
export const FETCH_FAVORITELIST_START = 'FETCH_FAVORITELIST_START';
export const FETCH_FAVORITELIST_SUCCESS = 'FETCH_FAVORITELIST_SUCCESS';
export const FETCH_FAVORITELIST_FAIL = 'FETCH_FAVORITELIST_FAIL';
// -----List of favorite movies data-----
export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';
// Add favorite
export const ADD_FAVORITE_START = 'ADD_FAVORITE_START';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';
// Remove favorite
export const REMOVE_FAVORITE_START = 'REMOVE_FAVORITE_START';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_FAIL = 'REMOVE_FAVORITE_FAIL';
