export const FETCH_POPULAR_MOVIES_START = 'FETCH_POPULAR_MOVIES_START';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_FAIL = 'FETCH_MOVIES_POPULAR_FAIL';

export const FETCH_TOP_RATED_MOVIES_START = 'FETCH_TOP_RATED_MOVIES_START';
export const FETCH_TOP_RATED_MOVIES_SUCCESS = 'FETCH_TOP_RATED_MOVIES_SUCCESS';
export const FETCH_TOP_RATED_MOVIES_FAIL = 'FETCH_TOP_RATED_MOVIES_FAIL';

export const FETCH_LATEST_START = 'FETCH_LATEST_START';
export const FETCH_LATEST_SUCCESS = 'FETCH_LATEST_SUCCESS';
export const FETCH_LATEST_FAIL = 'FETCH_LATEST_FAIL';
